[project]
name = "iceportalmagazinedownloader"
version = "0.2.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "requests>=2.32.4",
    "selenium>=4.34.2",
]
